# Auto-generated by Aspire for EF Core migration bundle.
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --chmod=0755 media-migrations /app/efbundle
ENTRYPOINT /app/efbundle -v --connection "$ConnectionStrings__mediadb"
