<script setup lang="ts">
interface Item{id:string;authorUserId:string;title?:string;content:string;status:number;isHidden:boolean;isParentHidden?:boolean;revision:number}
const {request,session}=useAdminApi();if(!session.value?.permissions.includes('content.moderate'))throw createError({statusCode:403})
const kind=ref('posts');const state=ref('all');const q=ref('');const page=ref(1);const items=ref<Item[]>([]);const total=ref(0);const busy=ref(false);const error=ref('');const selected=ref<Item|null>(null);const action=ref('hide');const reason=ref('');const modal=ref(false)
async function load(){busy.value=true;error.value='';try{const data=await request<{items:Item[];total:number}>(kind.value,{query:{q:q.value,state:state.value,page:page.value}});items.value=data.items;total.value=data.total}catch{error.value='内容加载失败，请稍后重试。'}finally{busy.value=false}}
function select(item:Item){selected.value=item;action.value=item.isHidden?'restore':'hide';reason.value='';modal.value=true}
async function submit(){if(!selected.value)return;busy.value=true;error.value='';try{await request(`${kind.value}/${selected.value.id}/${action.value}`,{method:'POST',body:{revision:selected.value.revision,reason:reason.value}});modal.value=false;await load()}catch(err){error.value=(err as {statusCode?:number}).statusCode===409?'记录已被处理，请刷新后重试。':'操作失败，请检查权限并重试。'}finally{busy.value=false}}
watch([kind,state],()=>{page.value=1;load()});onMounted(load)
</script>
<template><div><h1 class="title">内容管理</h1><p class="subtitle">处理结果会记录原因及操作者；已删除内容无法恢复。</p><div class="toolbar"><USelect v-model="kind" :items="[{label:'帖子',value:'posts'},{label:'评论',value:'comments'}]"/><USelect v-model="state" :items="[{label:'全部状态',value:'all'},{label:'正常',value:'published'},{label:'已下架',value:'hidden'},{label:'已删除',value:'deleted'}]"/><UInput v-model="q" placeholder="搜索内容" @keyup.enter="page=1;load()"/><UButton label="查询" :loading="busy" @click="page=1;load()"/></div><p v-if="error" class="error" role="alert">{{error}}</p><div class="table-wrap"><table><thead><tr><th>内容</th><th>作者</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td><div class="font-semibold">{{item.title??item.content.slice(0,90)}}</div><div class="muted">{{item.id}}</div></td><td class="muted">{{item.authorUserId}}</td><td><UBadge :color="item.status===2?'neutral':item.isHidden||item.isParentHidden?'warning':'success'" variant="soft">{{item.status===2?'已删除':item.isParentHidden?'父评论下架':item.isHidden?'已下架':'正常'}}</UBadge></td><td><UButton :label="item.isHidden?'查看并恢复':'查看并下架'" color="neutral" variant="outline" :disabled="item.status===2||!!item.isParentHidden" @click="select(item)"/></td></tr></tbody></table><div v-if="!items.length" class="empty">{{busy?'正在加载…':'没有符合条件的内容'}}</div></div><div class="pagination"><span class="muted">共 {{total}} 条 · 第 {{page}} 页</span><div class="actions"><UButton label="上一页" color="neutral" :disabled="page<=1||busy" @click="page--;load()"/><UButton label="下一页" color="neutral" :disabled="page*20>=total||busy" @click="page++;load()"/></div></div><UModal v-model:open="modal" :title="action==='hide'?'下架内容':'恢复内容'"><template #body><div class="detail">{{selected?.title}}<br>{{selected?.content}}</div><label class="block mb-2">处理原因</label><UTextarea v-model="reason" maxlength="500" class="w-full" placeholder="请输入明确的处理原因"/><p v-if="error" class="error">{{error}}</p></template><template #footer><UButton label="取消" color="neutral" variant="outline" @click="modal=false"/><UButton :label="action==='hide'?'确认下架':'确认恢复'" :disabled="!reason.trim()" :loading="busy" @click="submit"/></template></UModal></div></template>
