<script setup lang="ts">
interface Restriction{publishingRestricted:boolean;commentingRestricted:boolean;expiresAtUtc?:string;revision:number}
interface Item{userId:string;nickname?:string;restriction?:Restriction}
const {request,session}=useAdminApi();if(!session.value?.permissions.includes('users.restrict'))throw createError({statusCode:403})
const items=ref<Item[]>([]);const total=ref(0);const q=ref('');const page=ref(1);const error=ref('');const busy=ref(false);const selected=ref<Item|null>(null);const modal=ref(false);const publishing=ref(false);const commenting=ref(false);const expires=ref('');const reason=ref('')
async function load(){busy.value=true;try{const data=await request<{items:Item[];total:number}>('users',{query:{q:q.value,page:page.value}});items.value=data.items;total.value=data.total;error.value=''}catch{error.value='用户加载失败。'}finally{busy.value=false}}
function select(item:Item){selected.value=item;publishing.value=item.restriction?.publishingRestricted??false;commenting.value=item.restriction?.commentingRestricted??false;const expiry=item.restriction?.expiresAtUtc;expires.value=expiry?new Date(Date.parse(expiry)-new Date(expiry).getTimezoneOffset()*60000).toISOString().slice(0,16):'';reason.value='';modal.value=true}
function active(item:Item){return item.restriction&&(!item.restriction.expiresAtUtc||Date.parse(item.restriction.expiresAtUtc)>Date.now())}
async function save(){if(!selected.value)return;busy.value=true;try{await request(`users/${selected.value.userId}/restrictions`,{method:'POST',body:{publishingRestricted:publishing.value,commentingRestricted:commenting.value,expiresAtUtc:expires.value?new Date(expires.value).toISOString():null,revision:selected.value.restriction?.revision??0,reason:reason.value}});modal.value=false;await load()}catch(err){error.value=(err as {statusCode?:number}).statusCode===409?'记录已变更，请刷新后重试。':'保存失败，请检查到期时间和权限。'}finally{busy.value=false}}
onMounted(load)
</script>
<template><div><h1 class="title">用户管理</h1><p class="subtitle">管理发布和评论资格。关闭对应开关可解除限制。</p><div class="toolbar"><UInput v-model="q" placeholder="搜索昵称" @keyup.enter="page=1;load()"/><UButton label="查询" :loading="busy" @click="page=1;load()"/></div><p v-if="error" class="error" role="alert">{{error}}</p><div class="table-wrap"><table><thead><tr><th>用户</th><th>发布</th><th>评论</th><th>到期时间</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.userId"><td><div class="font-semibold">{{item.nickname??'未设置昵称'}}</div><div class="muted">{{item.userId}}</div></td><td>{{active(item)&&item.restriction?.publishingRestricted?'已限制':'正常'}}</td><td>{{active(item)&&item.restriction?.commentingRestricted?'已限制':'正常'}}</td><td class="muted">{{item.restriction?.expiresAtUtc?new Date(item.restriction.expiresAtUtc).toLocaleString():'未设置'}}</td><td><UButton label="管理限制" color="neutral" variant="outline" @click="select(item)"/></td></tr></tbody></table><div v-if="!items.length" class="empty">没有符合条件的用户</div></div><div class="pagination"><span class="muted">共 {{total}} 条 · 第 {{page}} 页</span><div class="actions"><UButton label="上一页" color="neutral" :disabled="page<=1" @click="page--;load()"/><UButton label="下一页" color="neutral" :disabled="page*20>=total" @click="page++;load()"/></div></div><UModal v-model:open="modal" title="管理社区功能限制"><template #body><div class="form"><p class="muted">{{selected?.userId}}</p><USwitch v-model="publishing" label="限制发布帖子"/><USwitch v-model="commenting" label="限制发表评论"/><div><label>到期时间（留空为长期有效）</label><UInput v-model="expires" type="datetime-local" class="w-full"/></div><div><label>处理原因</label><UTextarea v-model="reason" maxlength="500" class="w-full"/></div><p v-if="error" class="error">{{error}}</p></div></template><template #footer><UButton label="取消" color="neutral" variant="outline" @click="modal=false"/><UButton label="保存限制" :disabled="!reason.trim()" :loading="busy" @click="save"/></template></UModal></div></template>
